name: unit, integration, and regression tests

on:
  push:
  workflow_call:

jobs:
  static-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --locked

      - name: Unit tests
        run: make test-unit

      - name: Integration tests
        run: make test-integration
      
      - name: Regression tests
        run: make test-regression
