name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        default: "x.x.x"
      suffix:
        required: false
        type: string
        default: "test"
  release:
    types: [published]

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      GH_REGISTRY: ghcr.io
      GH_REPOSITORY: ${{ github.repository }}

    permissions:
      contents: read
      packages: write
      #attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Docker login
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ECR login
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::220625057922:role/dataforge-ecr-access-role
          aws-region: eu-central-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Define IMAGE:TAG name -> returned in output as tags
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.GH_REPOSITORY }}
            ${{ steps.login-ecr.outputs.registry }}/dataforge-220625057922
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.release.tag_name || format('{0}{1}', inputs.tag_name, inputs.suffix) }}
            type=sha,format=short

      # Build and push image
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      #- name: Generate artifact attestation
      #  uses: actions/attest@v4
      #  with:
      #    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #    subject-digest: ${{ steps.push.outputs.digest }}
      #    push-to-registry: true    
