name: Typecheck, Lint and Formatter

on:
  push:
  workflow_call:
  pull_request:
    types: [opened, reopened, synchronize]
    branch:
      - main

jobs:
  static-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --locked

      - name: Type-check
        run: make typecheck

      - name: Lint
        run: make lint
      
      - name: Format
        run: make format-check

